import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { BOMResult } from '@/types/bom';
import { ROOF_TYPE_LABELS, PROFILE_COLOR_LABELS, HOOK_TYPE_LABELS, PROFILE_TYPE_LABELS, ROOFING_TYPE_LABELS } from '@/data/products';

export const exportBOMToPDF = (result: BOMResult) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(30, 58, 95);
  doc.rect(0, 0, pageWidth, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Axxiom Solar', 14, 20);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text('Bill of Materials (BOM)', 14, 32);

  // Date
  doc.setFontSize(10);
  doc.text(`Date: ${new Date().toLocaleDateString('en-GB')}`, pageWidth - 14, 20, { align: 'right' });

  // Reset text color
  doc.setTextColor(0, 0, 0);

  // Configuration Summary
  let yPos = 55;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Configuration Summary', 14, yPos);

  yPos += 8;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  const configItems = [
    ['System Type:', ROOF_TYPE_LABELS[result.config.roof.roofType]],
    ['Total Panels:', `${result.totalPanels} (${result.config.panel.rows} rows × ${result.config.panel.columns} columns)`],
    ['Orientation:', result.config.panel.orientation === 'landscape' ? 'Landscape' : 'Portrait'],
    ['Panel Dimensions:', `${result.config.panel.height} × ${result.config.panel.width} × ${result.config.panel.thickness} mm`],
    ['Profile Color:', PROFILE_COLOR_LABELS[result.config.roof.profileColor]],
    ['Clamp Color:', PROFILE_COLOR_LABELS[result.config.roof.clampColor]],
  ];

  // Add slanted roof specific info
  if (result.config.roof.roofingType) {
    configItems.push(['Roofing Type:', ROOFING_TYPE_LABELS[result.config.roof.roofingType] || '-']);
  }
  if (result.config.roof.hookType) {
    configItems.push(['Hook Type:', HOOK_TYPE_LABELS[result.config.roof.hookType] || '-']);
  }
  if (result.config.roof.profileType) {
    configItems.push(['Profile Type:', PROFILE_TYPE_LABELS[result.config.roof.profileType] || '-']);
  }

  configItems.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label, 14, yPos);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 60, yPos);
    yPos += 6;
  });

  // Materials Table
  yPos += 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Bill of Materials', 14, yPos);

  autoTable(doc, {
    startY: yPos + 5,
    head: [['Product Code', 'Description', 'Needed', 'Packed', 'Quantity']],
    body: result.items.map((item) => [
      item.productCode,
      item.description,
      item.required.toString(),
      item.packaged.toString(),
      item.toOrder.toString(),
    ]),
    headStyles: {
      fillColor: [30, 58, 95],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'left',
    },
    bodyStyles: {
      fontSize: 9,
    },
    columnStyles: {
      0: { cellWidth: 35, fontStyle: 'bold' },
      1: { cellWidth: 'auto' },
      2: { cellWidth: 20, halign: 'center' },
      3: { cellWidth: 20, halign: 'center' },
      4: { cellWidth: 25, halign: 'center', fontStyle: 'bold' },
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
    margin: { left: 14, right: 14 },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount} - Generated by Axxiom Solar BOM Calculator`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  // Save
  const timestamp = new Date().toISOString().split('T')[0];
  doc.save(`Axxiom_BOM_${timestamp}.pdf`);
};
